### ISSUE TITLE
Build Failed for Unreal 5.3 and Unreal 5.4

### ISSUE THREAD

**Issue by NISP2709** [JSBSim-Team/jsbsim#1181]
### Discussed in https://github.com/JSBSim-Team/jsbsim/discussions/1180

<div type='discussions-op-text'>

<sup>Originally posted by **NISP2709** November  1, 2024</sup>
When I am trying to open the project the Unreal Projects states that to build the plugin manually, So I am writing the command to build it for both the engine version. For the Both the Engine I getting different errors. This are the following commands and errors that I am getting while building the plugin:

_I am not much of a programmer, Please guide if I am making some mistakes._

**Command Error for Unreal 5.3:**
```
RunUAT.bat BuildPlugin -plugin="C:\Users\DigiCon\Downloads\jsbsim-master\UnrealEngine\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin" -package="D:\Nish\Build\5.3\JSBSimFlightDynamicsModel"
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin=C:\Users\DigiCon\Downloads\jsbsim-master\UnrealEngine\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin -package=D:\Nish\Build\5.3\JSBSimFlightDynamicsModel
Initializing script modules...
Total script module initialization time: 0.63 s.
Executing commands...
Copying 573 file(s) using max 64 thread(s)
Reading plugin from D:\Nish\Build\5.3\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\Nish\Build\5.3\JSBSimFlightDynamicsModel\HostProject\HostProject.uproject" -plugin="D:\Nish\Build\5.3\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin" -noubtmakefiles -manifest="D:\Nish\Build\5.3\JSBSimFlightDynamicsModel\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
JSBSim Path Check OK: D:\Nish\Build\5.3\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\Source\ThirdParty\JSBSim\Lib\JSBSim.dll
Total execution time: 8.89 seconds
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element)
   at UnrealBuildTool.ModuleRules.IsValidForTarget(Type ModuleType, ReadOnlyTargetRules TargetRules, String& InvalidReason) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\ModuleRules.cs:line 1623
   at UnrealBuildTool.UEBuildTarget.AddAllValidModulesToTarget(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3886
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 3354
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 659
Took 9.24s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 0m 11s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
```

**Command Error for Unreal 5.4:**
```
RunUAT.bat BuildPlugin -plugin="C:\Users\DigiCon\Downloads\jsbsim-master\UnrealEngine\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin" -package="D:\Nish\Build\5.4\JSBSimFlightDynamicsModel"
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -plugin=C:\Users\DigiCon\Downloads\jsbsim-master\UnrealEngine\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin -package=D:\Nish\Build\5.4\JSBSimFlightDynamicsModel
Initializing script modules...
Total script module initialization time: 0.63 s.
Using C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
Executing commands...
Copying 573 file(s) using max 64 thread(s)
Reading plugin from D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin...
Building plugin for host platforms: Win64
Running: C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Program Files\Epic Games\UE_5.4\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\HostProject.uproject" -plugin="D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\JSBSimFlightDynamicsModel.uplugin" -noubtmakefiles -manifest="D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt
JSBSim Path Check OK: D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\Source\ThirdParty\JSBSim\Lib\JSBSim.dll
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\HostProject.uproject D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
Total of 0 written
C:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Experimental\UserToolBoxBasicCommand\Source\UserToolBoxBasicCommand\Public\EngineCommand.h(12): Error: Class 'UEngineCommand' shares engine name 'EngineCommand' with struct 'FEngineCommand' in D:\Nish\Build\5.4\JSBSimFlightDynamicsModel\HostProject\Plugins\JSBSimFlightDynamicsModel\Source\JSBSimFlightDynamicsModel\Public\FDMTypes.h(140)
Total execution time: 72.46 seconds
Took 72.69s to run dotnet.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\DigiCon\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.4\UBA-UnrealEditor-Win64-Development.txt)
AutomationTool executed for 0h 1m 14s
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
```

### Please Let m know where I am making mistake</div>

**Comment by bcoconni** [comment]
This issue is redundant with the discussion #1180.
Closed.
